version: '2.4'
services:
  front:
    container_name: ducksmanager-web
    image: "nginx:1.15"
    depends_on:
      - gateway
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - current:/var/www/html
    restart: always
    networks:
      - workspace_global-front-network
      - dm-network

  gateway:
    container_name: ducksmanager-php
    build:
      context: .
    restart: always
    volumes:
      - current:/var/www/html
    networks:
      - dm-network
      - dm-server_front-network

networks:
  dm-network:
  workspace_global-front-network:
    external: true
  dm-server_front-network:
    external: true

volumes:
  current:

